- src/org/thoughtcrime/securesms/ConversationActivity.java
when switching from a conversation with a subtitle to one without (an unknown contact), the subtitle wasn't being unset. I cleaned the logic up a bit to make sure we always set subtitle and title to their proper states, independent of what they were.
> set conversation actionbar statelessly

- src/org/thoughtcrime/securesms/util/GroupUtil.java
In the case that only the avatar was updated (or nothing was updated at all), the group update text would be blank. This changes it to the generic "group updated" text.
> fix empty group update messages

- src/org/thoughtcrime/securesms/crypto/MmsCipher.java
Traced a crash back to this issue.
> Fix NPE when encrypted MMS has bad base64 encoding

- res/values/themes.xml
After going through a seemingly infinite number of actionbar and actionmode-related theming attributes, this one for some reason is the right one.
For people searching, no it's not `actionModeStyle`, `popupMenuStyle`, `actionDropDownStyle`, or `actionModeBackground` in either your main theme or your ActionBar custom theme.
> Fix white-on-white ActionMode popup in dark theme

- src/org/thoughtcrime/securesms/BaseActionBarActivity.java
- src/org/thoughtcrime/securesms/BaseActivity.java
Proposal for temporary assurances that people can use the app: loosen criteria for the keycode workaround, and at the same time force the "three dots" overflow menu regardless of hardware on devices running  Android 4.x ROMs which seem to be the problem zone.
Fixes #2444
> Workaround LG-related menu issues, pt. 2

- AndroidManifest.xml
- androidTest/java/org/thoughtcrime/securesms/RegistrationActivityTest.java
- androidTest/java/org/thoughtcrime/securesms/RoutedInstrumentationTestCase.java
- androidTest/java/org/thoughtcrime/securesms/database/CanonicalAddressDatabaseTest.java
- androidTest/java/org/thoughtcrime/securesms/util/PhoneNumberFormatterTest.java
- androidTest/java/org/thoughtcrime/securesms/util/UtilTest.java
- build.gradle
Put the instrumentation in place to run Espresso 2 tests, plus an example test that a clean start and verifies the Register and Skip buttons are displayed.
> Add first Espresso interaction test

- res/xml/preferences_advanced.xml
@moxie0 looks like you missed this one in https://github.com/WhisperSystems/TextSecure/commit/a4e18c515c61674dbe04f93fecce2b71c91f840b ;)
> remove "Complete key exchanges" from advanced options

- src/org/thoughtcrime/securesms/database/MmsDatabase.java
- src/org/thoughtcrime/securesms/database/SmsDatabase.java
- src/org/thoughtcrime/securesms/jobs/PushDecryptJob.java
1) The group ID for jobs that process received messages was
previously set to the sender's e164.  This guaranteed
serialization of messages per-recipient, while allowing
processing of multiple recipients in parallel.  Unfortunately
in the case of groups, this results in out of order
conversations, since the "sender" for each message is
different.  And we can't determine that it was a group
message until *after* we process it.  So this change just
puts all message processing from all senders in one big queue.
2) Synchronization messages were always being displayed before
received messages, due to the "received time" for those
being set to the time they were sent.
Fixes #3618
Fixes #2385
// FREEBIE
> Fix two message ordering issues.

- res/drawable/last_seen_divider_text_background_dark.xml
- res/drawable/last_seen_divider_text_background_light.xml
- res/layout/conversation_item_last_seen.xml
- res/values/attrs.xml
- res/values/themes.xml
* API 25 emulator
* Android 4.2 phone
----------
Currently, Signal 3.30 crashes for me on Android 4.2 when it tries to inflate the new "last seen" divider in a conversation. I get
```
android.view.InflateException: Binary XML file line #11: Error inflating class TextView
```
caused by
```
android.content.res.Resources$NotFoundException: File res/drawable/last_seen_divider_text_background.xml from drawable resource ID #0x7f0201b8
```
caused by
```
java.lang.UnsupportedOperationException: Can't convert to color: type=0x2
```
Apparently, it's not possible to reference an attribute in an xml drawable on API <21, so we have to use separate light and dark theme drawables instead.
Tested in a 7.1 emulator and on my 4.2 device with both light and dark themes.
> Fix last seen divider crash on Android <5.0

- src/org/thoughtcrime/securesms/webrtc/PeerConnectionWrapper.java
* Samsung Galaxy S2 (i9100), Android 7.1.2
* Samsung Galaxy S3 (i9300), Android 7.1.2
----------
If Camera2Enumerator.isSupported() throws, consider Camera2Enumerator to
not be supported, log the Throwable, and use Camera1Enumerator instead.
Before this patch, an exception thrown by Camera2Enumerator.isSupported
would crash any Signal call (even if video was not enabled).
Fixes #6537
// FREEBIE
I experienced the same errors as described in #6537 on the two devices mentioned above. This patch makes video calls work for these devices.
> Fall back to Camera1Enumerator on exceptions (Fix for #6537)

- src/org/thoughtcrime/securesms/util/BitmapUtil.java
Fixes #7208.
On some phones, zooming in on large images (say, a 4k image) would be slow and stutter a lot. This is due to ZoomingImageView using a regular PhotoView instead of a SubsamplingScaleImageView. ZoomingImageView decides whether or not to use a SubsamplingScaleImageView depending on whether the image has a dimension larger than BitmapUtil.getMaxTextureSize(). 
However, while that method will determine the maximum size of an image that is _possible_ to render, it doesn't necessarily mean it can be rendered _efficiently_. There is some size at which some phones will have to continually re-upload a bitmap to the GPU, as seen in this systrace taken from a Moto E.
We could just use SubsamplingScaleImageView all the time (it has built-in logic to prevent tiling on smaller images), but …
> Reduce image stutter by using subsampling more often.

- res/menu/media_preview.xml
- res/values/strings.xml
- src/org/thoughtcrime/securesms/MediaPreviewActivity.java
- src/org/thoughtcrime/securesms/database/AttachmentDatabase.java
- src/org/thoughtcrime/securesms/database/Database.java
- src/org/thoughtcrime/securesms/database/MediaDatabase.java
- src/org/thoughtcrime/securesms/database/loaders/BucketedThreadMediaLoader.java
Added the ability to delete media via the media preview. A delete option is added to the action bar of the MediaPreviewActivity. When pressed:
* The attachment entry representing the media is deleted.
* If there are no other attachments for the linked MMS message, then the MMS entry is also deleted.
* The preview is closed.
[Video](https://github.com/signalapp/Signal-Android/files/1809293/delete-media-preview.zip)
**TODO**
**Test Cases**
* Deleted static image
* Deleted GIF
* Deleted video
* Ensured that messages are gone from the conversation view.
* Ensured that media is gone from the "all media" screen.
* Ensured that the delete option is not present for previews of unsent media.
* Simulated the DeleteMediaTask taking a long time, so the preview closes before the deletion is finished. …
> Allow deletion of media through preview.

- res/layout/media_overview_gallery_item.xml
- res/menu/media_overview_context.xml
- res/values/colors.xml
- res/values/strings.xml
- src/org/thoughtcrime/securesms/MediaGalleryAdapter.java
- src/org/thoughtcrime/securesms/MediaOverviewActivity.java
- src/org/thoughtcrime/securesms/MediaPreviewActivity.java
- src/org/thoughtcrime/securesms/util/AttachmentUtil.java
It is now possible to batch-delete media in the "media overview" screen. You can long press to enter multi-select mode. Then a delete button appears on the menu bar. After pressing delete, you will get a confirmation, and if the user confirms, the items will delete while a progress dialog shows.
[video](https://github.com/signalapp/Signal-Android/files/1816757/batch-delete-media.zip)
**Test Cases**
* Deleted a single image.
* Deleted multiple images.
* Deleted multiple images across section headers.
* Rotate the phone at every possible point in the flow.
**Unable to Test**
* Deleting one attachment from a message with multiple attachments. While this is technically possible, there's no way to create this scenario in the app today.
* [Moto X (2nd Generation), Android …
> Allow batch deletion of media.

- src/org/thoughtcrime/securesms/jobs/MmsSendJob.java
- src/org/thoughtcrime/securesms/jobs/PushGroupSendJob.java
- src/org/thoughtcrime/securesms/jobs/PushMediaSendJob.java
- src/org/thoughtcrime/securesms/jobs/SendJob.java
- src/org/thoughtcrime/securesms/util/MediaUtil.java
This PR strips EXIF metadata from all JPEG attachments before sending. Previously, it was being stripped from most images by our re-scaling process. However, smaller images would slip through and keep their metadata, possibly exposing things like photo location. 
This PR removes all EXIF metadata by re-encoding the JPEG. This keeps all of the visual effects of the EXIF tags (like orientation) by updating the image data itself, while removing all EXIF tags.
Fixes #5968
**Test Cases**
* Sending a small JPEG (that doesn't get resized) with lots of metadata, including orientation
* Sending a small JPEG (that doesn't get resized) with lots of metadata, excluding orientation
* Sending a large JPEG (that does get resized)
* Sending a JPEG with no metadata
* Sending a GIF
* Sending a PNG …
> Strip EXIF metadata from JPEG attachments.

- res/drawable/webrtc_camera_flip_button.xml
- res/drawable/webrtc_camera_front_button.xml
- res/drawable/webrtc_camera_rear_button.xml
- res/layout/webrtc_call_controls.xml
- res/values/strings.xml
- src/org/thoughtcrime/securesms/WebRtcCallActivity.java
- src/org/thoughtcrime/securesms/components/webrtc/WebRtcCallControls.java
- src/org/thoughtcrime/securesms/components/webrtc/WebRtcCallScreen.java
- src/org/thoughtcrime/securesms/events/WebRtcViewModel.java
- src/org/thoughtcrime/securesms/service/WebRtcCallService.java
- src/org/thoughtcrime/securesms/webrtc/CameraState.java
- src/org/thoughtcrime/securesms/webrtc/PeerConnectionWrapper.java
A button has been added to allow switching between the front and back camera during video calls. 
**To-Do**
**Test Cases**
* Simulate missing a back camera
* Simulate missing a front camera
* Simulate missing both cameras
* Being both the initiator and receiver of the call
* Pressing the toggle button really fast
* [Moto E (2nd Gen), Android 5.1, API 22](https://www.gsmarena.com/motorola_moto_e_(2nd_gen)-6986.php)
* [Moto X (2nd Gen), Android 7.1, API 25](https://www.gsmarena.com/motorola_moto_x_(2nd_gen)-6649.php)
* [Galaxy S3 Mini, Android 4.2.2. API 17](https://www.gsmarena.com/samsung_i8200_galaxy_s_iii_mini_ve-6190.php)
> Allow switching your camera in video calls.

- AndroidManifest.xml
- res/layout/activity_contact_name_edit.xml
- res/layout/item_editable_contact.xml
- res/values/strings.xml
- src/org/thoughtcrime/securesms/contactshare/ContactNameEditActivity.java
- src/org/thoughtcrime/securesms/contactshare/ContactNameEditViewModel.java
- src/org/thoughtcrime/securesms/contactshare/ContactShareEditActivity.java
- src/org/thoughtcrime/securesms/contactshare/ContactShareEditAdapter.java
- src/org/thoughtcrime/securesms/contactshare/ContactShareEditViewModel.java
This allows users to edit the name of a contact before they send it out. Special consideration was taken to support proper displayName generation based off of the character set of the name. If a name is composed _entirely_ of Chinese-Japanese-Korean characters, then we change the display name format to be:
```givenName familyName prefix suffix middleName```
From my research (and what I've been told by my friend who is a Chinese native), middle names basically don't exist in these cultures, so it was suggested just to throw it at the end.
[Demo Video](https://github.com/signalapp/Signal-Android/files/2013953/contact-name-editing.zip)
> Allow editing of contact names during contact sharing.

- build.gradle
- src/org/thoughtcrime/securesms/database/helpers/SQLCipherOpenHelper.java
Previously, SQLCipher's memory usage would grow indefinitely, up until it hit the end of the cursor. This leaves us open to OOM errors on large datasets. We've now switched to a release where the
memory used by the cursor can be bounded.
Performance seems largely unaffected. Basic query times appear to be the same on my 2014 Moto E. The main difference is that because there's a memory ceiling on a cursor, if it hits that memory ceiling, it has to requery and refill the cursor window. 
On a conversation with 18,500 messages (again, on my 2014 Moto E), this takes just under 1 second. Because the cursor is refilled on the main thread, that means the UI has a very noticeable "hiccup". However, I only experienced this hiccup when I set the memory ceiling very low (128 KB). At it's current …
> Upgrade SQLCipher to respect a max window size.

- src/org/thoughtcrime/securesms/search/SearchFragment.java
- src/org/thoughtcrime/securesms/util/StickyHeaderDecoration.java
The sticky header cache was keeping views across rotations, causing them to render incorrectly afterwards. I added a method to invalidate the header layouts after rotation.
Fixes #7890.
> Fix search header rendering after rotation.

- AndroidManifest.xml
- src/org/thoughtcrime/securesms/jobmanager/Job.java
- src/org/thoughtcrime/securesms/jobmanager/JobConsumer.java
- src/org/thoughtcrime/securesms/jobmanager/JobParameters.java
- src/org/thoughtcrime/securesms/jobmanager/JobQueue.java
- src/org/thoughtcrime/securesms/jobmanager/requirements/BackoffReceiver.java
- src/org/thoughtcrime/securesms/jobmanager/requirements/NetworkBackoffRequirement.java
- src/org/thoughtcrime/securesms/jobmanager/requirements/NetworkRequirement.java
- src/org/thoughtcrime/securesms/jobmanager/requirements/Requirement.java
- src/org/thoughtcrime/securesms/jobmanager/requirements/SimpleRequirement.java
- src/org/thoughtcrime/securesms/jobs/PushContentReceiveJob.java
- src/org/thoughtcrime/securesms/jobs/PushSendJob.java
- src/org/thoughtcrime/securesms/jobs/SmsSendJob.java
- src/org/thoughtcrime/securesms/jobs/SmsSentJob.java
- src/org/thoughtcrime/securesms/jobs/requirements/MasterSecretRequirement.java
- src/org/thoughtcrime/securesms/jobs/requirements/NetworkOrServiceRequirement.java
- src/org/thoughtcrime/securesms/jobs/requirements/ServiceRequirement.java
- src/org/thoughtcrime/securesms/jobs/requirements/SqlCipherMigrationRequirement.java
Previously, we would retry messages a fixed number of times, then declare them to be failed, prompting the user to manually retry. Now we will keep retrying message sends for up to 24 hours, using exponential backoff to throttle attempts.
Fixes #7888
> Keep retrying message sends for 24 hours.

- src/org/thoughtcrime/securesms/jobs/PushGroupSendJob.java
- src/org/thoughtcrime/securesms/jobs/PushMediaSendJob.java
- src/org/thoughtcrime/securesms/jobs/PushSendJob.java
- src/org/thoughtcrime/securesms/jobs/PushTextSendJob.java
Previously, we were running this job in PushSendJob#onCanceled(). However, with the new retry logic, this won't happen for 24 hours.
Instead, we now schedule the job in PushSendJob#onRetry().
It's worth noting that ServiceOutageDetectionJob throttles itself to be once every 60s and is non-persistent.
> Update scheduling of ServiceOutageDetectionJob.

- src/org/thoughtcrime/securesms/contactshare/ContactUtil.java
- src/org/thoughtcrime/securesms/database/ThreadDatabase.java
- src/org/thoughtcrime/securesms/notifications/MessageNotifier.java
Previously, contact shares would be displayed as "Media Message". Now it'll show the same as it does in a notification, namely ":bust_in_silhouette: {contact-name}".
(Note: the Galaxy S3 Mini contact name is, in fact ":ghost: Galaxy S3 Mini".
* [Moto E (2nd Gen), Android 5.1, API 22](https://www.gsmarena.com/motorola_moto_e_(2nd_gen)-6986.php)
> Fix conversation snippet for contact shares.

- src/org/thoughtcrime/securesms/ConversationItem.java
- src/org/thoughtcrime/securesms/util/AttachmentUtil.java
1) There was an issue where we wouldn't auto-download group syncs.
2) There was another issue where we didn't show the download controls
for messages you sent yourself.
This PR addresses both of these.
Fixes #7920
> Fixed issue where self-sends didn't auto download.

- src/org/thoughtcrime/securesms/jobs/PushDecryptJob.java
- src/org/thoughtcrime/securesms/jobs/PushGroupSendJob.java
- src/org/thoughtcrime/securesms/jobs/PushGroupUpdateJob.java
We will now check for updates to the expiring message time when receiving a group update event, as well as send the expiring message time when sending a group update event.
The primary use case of doing this is so when a new person is added to a group, they will also be told the expiring message timer. Previously, someone who was just added to the group wouldn't get the expiring message time until an actual message was sent.
* [Moto E (2nd Gen), Android 5.1, API 22](https://www.gsmarena.com/motorola_moto_e_(2nd_gen)-6986.php)
> Send/receive the expiring message timer for group updates.

- src/org/thoughtcrime/securesms/ConversationItem.java
- src/org/thoughtcrime/securesms/database/MmsDatabase.java
- src/org/thoughtcrime/securesms/sms/MessageSender.java
For self-sends, we were never marking attachments as uploaded. I made it so that happens now, but to prevent it for showing for already-sent messages, we also don't show controls for self-send conversations.
> Fix progress bar showing for self-sends.

- src/org/thoughtcrime/securesms/database/MmsDatabase.java
- src/org/thoughtcrime/securesms/database/SmsDatabase.java
Previously, we'd always use the value desktop gave us. However, if we have an earlier read time locally, we want to use that instead.
> Use earlier read timestamp when syncing read status with desktop.

- src/org/thoughtcrime/securesms/ApplicationContext.java
- src/org/thoughtcrime/securesms/crypto/KeyStoreHelper.java
- src/org/thoughtcrime/securesms/logging/AndroidLogger.java
- src/org/thoughtcrime/securesms/logging/CustomSignalProtocolLogger.java
- src/org/thoughtcrime/securesms/logging/GrowingBuffer.java
- src/org/thoughtcrime/securesms/logging/Log.java
- src/org/thoughtcrime/securesms/logging/LogFile.java
- src/org/thoughtcrime/securesms/logging/LogSecretProvider.java
- src/org/thoughtcrime/securesms/logging/PersistentLogger.java
- src/org/thoughtcrime/securesms/logging/UncaughtExceptionLogger.java
- src/org/thoughtcrime/securesms/logsubmit/SubmitLogFragment.java
- src/org/thoughtcrime/securesms/util/TextSecurePreferences.java
- src/org/thoughtcrime/securesms/util/Util.java
We have a problem where our debug logs don't go back very far. Right now, we rely on locally polling logcat. If we want to save more logs, we'll have to save them ourselves.
To do so, I've created a new logging layer called that mimics the interface of `Log`. You can add different `Loggers` to the new system. To start, I've added two Loggers: `AndroidLogger` and `PersistentLogger`. AndroidLogger just forwards everything to the standard Log command, while PersistentLogger persists logs on disk.
PersistentLogger works as follows:
- All work is done on a dedicated single-thread executor to prevent slowing down other parts of the app.
- Logs are written to a file until it hits a certain line length, at which point that file will be closed and a new one is started.
- When a new log is started, …
> Added new logger.

- AndroidManifest.xml
- res/values/strings.xml
- src/org/thoughtcrime/securesms/ApplicationContext.java
- src/org/thoughtcrime/securesms/ExperienceUpgradeActivity.java
- src/org/thoughtcrime/securesms/jobs/GcmRefreshJob.java
- src/org/thoughtcrime/securesms/jobs/LocalBackupJob.java
- src/org/thoughtcrime/securesms/jobs/PushDecryptJob.java
- src/org/thoughtcrime/securesms/notifications/AbstractNotificationBuilder.java
- src/org/thoughtcrime/securesms/notifications/FailedNotificationBuilder.java
- src/org/thoughtcrime/securesms/notifications/LocaleChangedReceiver.java
- src/org/thoughtcrime/securesms/notifications/NotificationChannels.java
- src/org/thoughtcrime/securesms/service/ApplicationMigrationService.java
- src/org/thoughtcrime/securesms/service/GenericForegroundService.java
- src/org/thoughtcrime/securesms/service/KeyCachingService.java
- src/org/thoughtcrime/securesms/service/MessageRetrievalService.java
- src/org/thoughtcrime/securesms/service/UpdateApkReadyListener.java
- src/org/thoughtcrime/securesms/webrtc/CallNotificationBuilder.java
Bucket our notifications into channels. Required to target API 26.
See `NotificationChannels.java` for an overview of all of the channels.
Here's a screenshot of what our notifications settings look like on a Nexus 5X running Android 8.1.
It's worth noting that the  "Uncategorized" category will disappear once we increase our API target.
* [Nexus 5X, Android 8.1, API 27](https://www.gsmarena.com/lg_nexus_5x-7556.php)
> Add notification channel support.

- res/layout/conversation_input_panel.xml
- res/menu/conversation.xml
- res/values/attrs.xml
- res/values/dimens.xml
- res/values/themes.xml
- src/org/thoughtcrime/securesms/ConversationActivity.java
- src/org/thoughtcrime/securesms/components/HidingLinearLayout.java
Previously, we'd only show the attachment button when the user had yet to enter any text. To add an attachment after text was entered, you'd have to go to the three-dot menu. Now we just show a little attach button in the text area.
I also took the opportunity to clean up other button paddings and stuff in the compose area so things look better and react to text sizes more predictably.
[Video Demo](https://github.com/signalapp/Signal-Android/files/2278703/attachment-button.zip)
* [Nexus 5X, Android 8.1, API 27](https://www.gsmarena.com/lg_nexus_5x-7556.php)
> Show attachment button while composing text.

- build.gradle
- res/values/strings.xml
- src/org/thoughtcrime/securesms/ConversationActivity.java
- src/org/thoughtcrime/securesms/RecipientPreferenceActivity.java
- src/org/thoughtcrime/securesms/dependencies/SignalCommunicationModule.java
- src/org/thoughtcrime/securesms/jobs/MultiDeviceBlockedUpdateJob.java
- src/org/thoughtcrime/securesms/jobs/MultiDeviceGroupUpdateJob.java
- src/org/thoughtcrime/securesms/jobs/PushDecryptJob.java
- src/org/thoughtcrime/securesms/jobs/PushReceivedJob.java
- src/org/thoughtcrime/securesms/util/GroupUtil.java
Groups can now be blocked just like individual contacts. This will prevent the ability to be re-added to a group after you've left it.
This also fixes the situation where we block group-leave messages, preventing blocked contacts from leaving groups (Fixes #7970).
Also, this forced us to upgrade libsignal-service, which fixes the websocket timeout issues. Thanks to @dpapavas! (Fixes #6644)
* [Nexus 5X, Android 8.1, API 27](https://www.gsmarena.com/lg_nexus_5x-7556.php)
> Add the ability to block groups.

- res/values/strings.xml
- src/org/thoughtcrime/securesms/ApplicationContext.java
- src/org/thoughtcrime/securesms/dependencies/SignalCommunicationModule.java
- src/org/thoughtcrime/securesms/gcm/GcmBroadcastReceiver.java
- src/org/thoughtcrime/securesms/jobs/PushContentReceiveJob.java
- src/org/thoughtcrime/securesms/jobs/PushDecryptJob.java
- src/org/thoughtcrime/securesms/jobs/PushNotificationReceiveJob.java
- src/org/thoughtcrime/securesms/jobs/PushReceivedJob.java
- src/org/thoughtcrime/securesms/service/MessageRetrievalService.java
- src/org/thoughtcrime/securesms/util/PowerManagerCompat.java
- src/org/thoughtcrime/securesms/util/TextSecurePreferences.java
After switching to WorkManager, we ran into situations where jobs to download messages after receiving a GCM push were being delayed. To combat this, this PR makes efforts to download the messages ASAP, starting a foreground service if necessary.
* [Moto X (2nd Gen), Android 7.1, API 25](https://www.gsmarena.com/motorola_moto_x_(2nd_gen)-6649.php)
* [Google Pixel 2, Android 9.0, API 28](https://www.gsmarena.com/google_pixel_2-8733.php)
> Ensure download of GCM messages.

- build.gradle
- src/org/thoughtcrime/securesms/jobs/MmsDownloadJob.java
- src/org/thoughtcrime/securesms/service/BootReceiver.java
- src/org/thoughtcrime/securesms/service/GenericForegroundService.java
- src/org/thoughtcrime/securesms/service/KeyCachingService.java
We need to increase our targetSdk version to 26 to comply with Play Store policy. A lot of the work that needed to happen for this migration was done through our migration to WorkManager. This PR cleans up the last few things that I've found.
1. GenericForegroundService needs to be started with startForegroundService, since it can be started when the app is in a backgrounded state. This means we also _always_ need to call startForeground in the service. However, by always posting with the same notification ID and content, no flickering occurs on my test devices.
1. We had a boot receiver that would start MessageRetrievalService. Instead, I just schedule a message pull, which should have a similar effect.
1. We previously were starting KeyCachingService if we went to get the MasterSecret. …
> Bump targetSdkVersion to 26.

- src/org/thoughtcrime/securesms/camera/Camera1Controller.java
- src/org/thoughtcrime/securesms/camera/Camera1Fragment.java
- src/org/thoughtcrime/securesms/camera/FlipTransformation.java
Some phones, notably the Pixel 3, had some problems with scaling after taking photos. This fixes it by 
using the takePicture API instead of pulling the bitmap from the TextureView.
As a nice side-effect, Pixel 2/3 will give us back the visual-core-optimized images, so those phones will get nicer photos. And most phones in general will at least give back smoother/less noisy photos.
Fixes #8292
* [Google Pixel 3, Android 9.0, API 28](https://www.gsmarena.com/google_pixel_3-9256.php)
* [Moto E (2nd Gen), Android 5.1, API 22](https://www.gsmarena.com/motorola_moto_e_(2nd_gen)-6986.php)
* [Google Pixel, Android 9.0, API 28](https://www.gsmarena.com/google_pixel-8346.php)
* [Google Pixel 2, Android 9.0, API 28](https://www.gsmarena.com/google_pixel_2-8733.php)
* [Moto G4, …
> Fix camera scaling issues on some phones.

- src/org/thoughtcrime/securesms/dependencies/ApplicationDependencyProvider.java
- src/org/thoughtcrime/securesms/util/AlarmSleepTimer.java
This pull request is the reincarnation of https://github.com/signalapp/libsignal-service-java/pull/70 because @alan-signal requested the following changes:
* Move the class RealtimeSleepTimer from from libsignal-service-java to Signal-Android
* rename it to AlarmSleepTimer
For any other info on this change please read [original request](https://github.com/signalapp/libsignal-service-java/pull/70), and especially [alans post](https://github.com/signalapp/libsignal-service-java/pull/70#issuecomment-551890303).
I provided a [test build](https://github.com/theBoatman/fixing-signal/blob/master/Signal-website-universal-release-4.49.17-sleepfix2.apk) if anyone wants to try it out.
If there is any problem or the need for further changes feel free to ask.
> fixing RealtimeSleepTimer to work in concurrent threads
