androidTest/java/org/thoughtcrime/securesms/TextSecureTestCase.java
androidTest/java/org/thoughtcrime/securesms/database/CanonicalAddressDatabaseTest.java
androidTest/java/org/thoughtcrime/securesms/database/PartDatabaseTest.java
androidTest/java/org/thoughtcrime/securesms/jobs/CleanPreKeysJobTest.java
androidTest/java/org/thoughtcrime/securesms/jobs/DeliveryReceiptJobTest.java
androidTest/java/org/thoughtcrime/securesms/util/PhoneNumberFormatterTest.java

Due to https://code.google.com/p/dexmaker/issues/detail?id=2 still being unresolved.

workaround dexmaker bug in test cases

---

src/org/thoughtcrime/securesms/mms/PartParser.java

don't fail on null received text parts

---

AndroidManifest.xml
build.gradle
res/layout/conversation_item_received.xml
res/layout/conversation_list_item_view.xml
res/layout/group_create_activity.xml
res/layout/push_contact_selection_list_item.xml
src/org/thoughtcrime/securesms/ConversationActivity.java
src/org/thoughtcrime/securesms/ConversationItem.java
src/org/thoughtcrime/securesms/ConversationListItem.java
src/org/thoughtcrime/securesms/GroupCreateActivity.java
src/org/thoughtcrime/securesms/ShareListItem.java
src/org/thoughtcrime/securesms/components/ImageDivet.java
src/org/thoughtcrime/securesms/contacts/ContactPhotoFactory.java
src/org/thoughtcrime/securesms/contacts/ContactSelectionListAdapter.java
src/org/thoughtcrime/securesms/recipients/AvatarGenerator.java
src/org/thoughtcrime/securesms/recipients/Recipient.java
src/org/thoughtcrime/securesms/recipients/RecipientProvider.java
src/org/thoughtcrime/securesms/util/BitmapUtil.java
src/org/thoughtcrime/securesms/util/BitmapWorkerRunnable.java

rounded ImageView instead of Bitmap, crop-select

---

res/values/plurals.xml
res/values/strings.xml
src/org/thoughtcrime/securesms/ConversationItem.java
src/org/thoughtcrime/securesms/ConversationListItem.java
src/org/thoughtcrime/securesms/util/DateUtils.java

Also opens us up to use relative dates ("3 mins", "now") in conversation items.

more succinct relative dates

---

AndroidManifest.xml
src/org/thoughtcrime/securesms/ConversationActivity.java
src/org/thoughtcrime/securesms/MediaPreviewActivity.java
src/org/thoughtcrime/securesms/database/ApnDatabase.java
src/org/thoughtcrime/securesms/database/TextSecureDirectory.java

Benchmarked with simulated high usage (open many conversations long and small with scrolling and many media previews), forced a GC, then took a `adb shell dumpsys meminfo org.thoughtcrime.securesms`.
Found leaks with heap dumps and MAT.
```
Applications Memory Usage (kB):
Pss  Private  Private  Swapped     Heap     Heap     Heap
Total    Dirty    Clean    Dirty     Size    Alloc     Free
------   ------   ------   ------   ------   ------   ------
Native Heap       16       16        0        0    18356    16939     1416
Dalvik Heap    69322    68912        0        0    90952    76586    14366
...
TOTAL   110803   101200     6444        0   109308    93525    15782
Objects
Views:     4813         ViewRootImpl:        6
AppContexts:       47           Activities:       44
Assets:        7 …
```

memory leak fixes, batch one

---

src/org/thoughtcrime/securesms/database/MmsDatabase.java

Prevent NPE when MMS's FROM PduHeader is missing

---

src/org/thoughtcrime/securesms/mms/MmsConnection.java

Fix NPE when InetAddress.getByName() is null

---

src/org/thoughtcrime/securesms/ConversationActivity.java
src/org/thoughtcrime/securesms/TransportOption.java
src/org/thoughtcrime/securesms/TransportOptions.java
src/org/thoughtcrime/securesms/components/SendButton.java
src/org/thoughtcrime/securesms/util/EncryptedSmsCharacterCalculator.java
src/org/thoughtcrime/securesms/util/PushCharacterCalculator.java
src/org/thoughtcrime/securesms/util/SmsCharacterCalculator.java

As the final installment of my Winter Cleaning Sunday™
Fixes #1841

Un-jank character count indicators

---

src/org/thoughtcrime/securesms/service/SmsListener.java

Support matching to account for telcos inserting SMS prefixes.

---

build.gradle

adds memory information to debug output

update libpastelog to 1.0.6

---

src/org/thoughtcrime/securesms/ConversationItem.java

fix NPE for incoming failed messages

---

src/org/thoughtcrime/securesms/database/MmsDatabase.java

Fix NPE when 'from' missing in NotificationInd

---

build.gradle
proguard-appcompat-v7.pro
proguard-dagger.pro
proguard-google-play-services.pro
proguard-jackson.pro
proguard-rounded-image-view.pro
proguard-spongycastle.pro
proguard-sqlite.pro
proguard-square-okhttp.pro
proguard-square-okio.pro
proguard.cfg

Move toward a "normal-style" proguard file. This cuts our class usage down significantly more.

proguard refactoring

---

src/org/thoughtcrime/securesms/database/MmsDatabase.java

There appeared to be multiple race conditions leading to the issues in #3051.
First, we needed to wait until the thumbnail for the draft attachment is generated before sending so it can be passed through to be inserted into the PartDatabase properly. Otherwise, we get a race that generates two thumbnails and takes *way* more memory.
Second, it seems like there's a race between the message being inserted into MmsDatabase and the parts being inserted into the part database. The CursorLoader would get notified that the dataset changed underneath it, and if the parts weren't inserted into the database by the time the listview refreshed, there would be no media slides available. To fix this, I just threw the message insertion into a transaction so we can still get the messageId properly, but …

fix race conditions around sending attachments.

---

res/layout/conversation_list_item_view.xml
res/values/strings.xml
src/org/thoughtcrime/securesms/ConversationActivity.java
src/org/thoughtcrime/securesms/ConversationListAdapter.java
src/org/thoughtcrime/securesms/ConversationListItem.java
src/org/thoughtcrime/securesms/components/ThumbnailView.java
src/org/thoughtcrime/securesms/database/AttachmentDatabase.java
src/org/thoughtcrime/securesms/database/DatabaseFactory.java
src/org/thoughtcrime/securesms/database/DraftDatabase.java
src/org/thoughtcrime/securesms/database/MmsDatabase.java
src/org/thoughtcrime/securesms/database/ThreadDatabase.java
src/org/thoughtcrime/securesms/database/model/ThreadRecord.java

Display thumbnail previews for images in conversation list.

---

res/values/strings.xml

Fix "Repeat new passphrase" spelling

---

res/values/strings.xml
res/xml/preferences.xml

Extract "Devices" preference category title to string resource

---

src/org/thoughtcrime/securesms/RecipientPreferenceActivity.java

fix crash in RecipientPreferenceActivity

---

res/layout/quick_camera_controls.xml
res/layout/quick_camera_controls_land.xml
src/org/thoughtcrime/securesms/ConversationActivity.java
src/org/thoughtcrime/securesms/components/camera/CameraView.java
src/org/thoughtcrime/securesms/components/camera/QuickAttachmentDrawer.java

* Disable shutter button until camera is ready for capture
* Reset the surface when the camera has been closed to prevent ghost frames
* Added some performance time logging to give us more insight if people have slow camera inits.

Resolve some direct capture UX issues

---

src/org/thoughtcrime/redphone/audio/IncomingRinger.java
src/org/thoughtcrime/redphone/audio/OutgoingRinger.java

* Emulator, Android 5.1
----------
I hope this fixes #5298, but I couldn't reproduce the crash. @2-4601 could you please test this?
// FREEBIE

Don't stop MediaPlayers before releasing them

---

src/org/thoughtcrime/securesms/ConversationAdapter.java

- [x ] I have read [how to contribute](https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [x ] I have signed the [Contributor Licence Agreement](https://whispersystems.org/cla/)
- [x ] I am following the [Code Style Guidelines](https://github.com/WhisperSystems/Signal-Android/wiki/Code-Style-Guidelines)
- [x ] I have tested my contribution on these devices:
* Nextbit Robin, Android 6.0.1
* Nexus 5X, Android 7
- [x ] My contribution is fully baked and ready to be merged as is
- [ x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)
- [x ] I have made the choice whether I want the …

Fix typo that breaks build.

---

res/layout/contact_selection_list_fragment.xml
res/layout/contact_selection_list_item.xml
res/layout/contact_selection_recyclerview_header.xml

// FREEBIE
* AVD, 7.1.1
------
Fixes #6588

Fix contact selection layout merge

---

CONTRIBUTING.md

* Local Markdown interpreter on my laptop.
* GitHub's Markdown interpreter in my forked repository.
----------
This commit revises the contribution guidelines, fixes a few outdated links, and adds some new information about Pull Requests.

Update the contribution guidelines.

---

build.gradle
res/drawable/header_search_background.xml
res/layout/fragment_search.xml
res/layout/header_search_result.xml
res/layout/load_more_header.xml
res/values/strings.xml
src/org/thoughtcrime/securesms/ConversationActivity.java
src/org/thoughtcrime/securesms/ConversationFragment.java
src/org/thoughtcrime/securesms/ConversationListActivity.java
src/org/thoughtcrime/securesms/ConversationListItem.java
src/org/thoughtcrime/securesms/DatabaseUpgradeActivity.java
src/org/thoughtcrime/securesms/ShareActivity.java
src/org/thoughtcrime/securesms/components/SearchToolbar.java
src/org/thoughtcrime/securesms/contacts/ContactsDatabase.java
src/org/thoughtcrime/securesms/database/CursorList.java
src/org/thoughtcrime/securesms/database/DatabaseFactory.java
src/org/thoughtcrime/securesms/database/MmsSmsDatabase.java
src/org/thoughtcrime/securesms/database/SearchDatabase.java
src/org/thoughtcrime/securesms/database/ThreadDatabase.java
src/org/thoughtcrime/securesms/database/helpers/SQLCipherOpenHelper.java
src/org/thoughtcrime/securesms/database/loaders/ConversationLoader.java
src/org/thoughtcrime/securesms/search/SearchFragment.java
src/org/thoughtcrime/securesms/search/SearchListAdapter.java
src/org/thoughtcrime/securesms/search/SearchRepository.java
src/org/thoughtcrime/securesms/search/SearchViewModel.java
src/org/thoughtcrime/securesms/search/model/MessageResult.java
src/org/thoughtcrime/securesms/search/model/SearchResult.java
src/org/thoughtcrime/securesms/util/Debouncer.java

This PR allows the search bar in the conversation list to search not only conversations, but also contacts and messages (!). This is done by using SQLite's full-text search feature.
[Demo Video](https://github.com/signalapp/Signal-Android/files/1929639/fts.zip)
_Note: Clicking "load full conversation" takes ~5s in the video because the conversation is approximately 37,000 messages long. Load time tends to scale roughly linearly, so conversations with ~18,500 messages complete in a little under 2.5 seconds on this 2014 mid-tier phone (Moto X 2nd Gen)._
While implementing this feature, I took the opportunity to bring in some of the new [Android Architecture Components](https://developer.android.com/topic/libraries/architecture/index.html), specifically ViewModels. The search feature has …

Implement full-text search.

---

AndroidManifest.xml
src/org/thoughtcrime/securesms/ConversationItem.java
src/org/thoughtcrime/securesms/service/ExpirationListener.java
src/org/thoughtcrime/securesms/service/ExpiringMessageManager.java

Mostly want to get a review for the failsafe I put in. Wanted to have some place where we can be extra sure that we don't render an expired message.
Fixes #7906

Fix disappearing message corner case.

---

res/layout/registration_activity.xml
res/values/strings.xml
src/org/thoughtcrime/securesms/RegistrationActivity.java

Added a link to go signal.org/legal during registration.

Show a link for privacy policy during registration.

---

src/org/thoughtcrime/securesms/contacts/avatars/ContactColors.java

Properly map hashed legacy colors to the new color palette.

---

app/src/main/res/values/strings.xml

* Device A, Android X.Y.Z
* Device B, Android Z.Y
* Virtual device W, Android Y.Y.Z
1) I haven't tested, since it's just a copy change. If that's truly necessary, I'll figure out how to test (I've never done mobile development).
2) There's no open issue. If that's a prerequisite, I'll open one.
----------
In response to [concerns](https://twitter.com/RealSexyCyborg/status/1197695344575799296) about Signal's UI around 3rd party keyboards, someone [suggested](https://twitter.com/orbitala/status/1351162690895540224) borrowing from Telegram's UI, and Moxie [agreed](https://twitter.com/moxie/status/1351205613645258756) it's worth consideration.
I'm not a mobile dev, so this PR might be completely inadequate. But hopefully it's a decent start.

Update incognito keyboard copy

---

app/src/main/java/org/thoughtcrime/securesms/preferences/AppProtectionPreferenceFragment.java
app/src/main/res/layout/incognito_learn_more.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences_app_protection.xml

Updates the copy and adds a learn more link.

Refine incognito keyboard setting string.
